### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by POInanodesu** [QQMiniBot/QQMini.Issues#1]
## 请描述遇到的问题
**请用简单的一句话来描述问题**
修改群名片事件，会出现QQ号小于10000的情况，然后报错

## 是否已经在网络上搜索过解决方案？
**如果我发现了重复的问题，我会将此的问题关闭。填写 “是” 或 “否”**
 是

## 运行环境
**请附上相关的运行环境，请填写列出的项目**

* SDK版本：1.0.20.1202-Beta
* 开发语言：C#
* 操作系统：Windows Server 2012
* .NET版本：4.8
* MSBuild版本：
* Visual Studio 版本：2019

## 详细问题描述
**请详细的描述一下遇到的问题**
修改群名片频繁弹出 无法将小于 “10000” 的值初始化为 QQ 的错误

## 异常堆栈
**请将异常堆栈信息复制到此处方便我分析**
错误代码：-2146232828
错误信息：
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.ArgumentOutOfRangeException: 无法将小于 “10000” 的值初始化为 QQ
参数名: id
   在 QQMini.PluginSDK.Core.Model.QQ..ctor(Int64 id)
   在 QQMini.PluginSDK.Core.Model.QMGroupMemberCardChangeEventArgs..ctor(Int32 type, Int32 subType, Int64 robotQQ, Int64 fromGroup, Int64 fromQQ, IntPtr newCard)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Activator.CreateInstance(Type type, Object[] args)
   在 QQMini.PluginSDK.Core.PluginBase.QQMini.PluginInterface.Core.IPlugin.PushNewEvent(Int32 type, Int32 subType, IntPtr[] datas)

## 复现步骤
**请将问题的复现步骤的详细操作方式告诉我**
管理员或群主使用PCQQ对群友的群名片进行修改，快速修改成不同长度的群昵称就会弹出报错

## 联系方式
**请留下联系方式，方便我联系你解决问题**
POI

**Comment by Jie2GG** [comment]
问题已收录

**Comment by Jie2GG** [comment]
您好, 您的问题已经被定位. 由于TX的限制, 在频繁修改时返回的 FromQQ 为 0, 因此产生此问题, 请不要过于频繁的变更群名片. 该问题已经在测试版中被解决! 感谢您的反馈.
